name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Usar la versión correcta de Node.js

      - uses: actions/checkout@v2

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            .buildozer_global
            .buildozer
            $HOME/android-sdk # Agrega el directorio de Android SDK a la caché
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.get-date.outputs.date }}-

      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install distutils
        run: sudo apt-get install -y --reinstall python3-distutils

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer

      - name: Install Cython
        run: pip install cython

      - name: Download and unzip Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O sdk-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          unzip -qq sdk-tools.zip -d $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
        env:
          RUNNER_TOOL_CACHE: ${{ runner.temp }}

      - name: Install Android SDK Build-Tools 34
        run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"

      - name: Install Aidl
        run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"

      - name: Verify Buildozer installation
        run: buildozer --version

      - name: Change permissions of .git/config
        run: chmod 777 .git/config

      - name: Build with Buildozer
        id: build
        run: |
          buildozer android debug || (echo "Buildozer build failed"; exit 1)
          echo "Build completed"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
